name: widget_explore_hemansee
description: Flutter project to explore dart widgets.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0-427.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  #  Enhance UI :
  flutter_otp_text_field: ^1.1.1
  cherry_toast: ^1.8.0
  fluttertoast: ^8.2.4

  #  Image management:
  image_picker: ^1.0.7
  cached_network_image: ^3.3.1

  #  Firebase :
  firebase_core: ^2.24.2
  google_sign_in: ^6.2.1
  firebase_auth: ^4.17.5
  firebase_storage: ^11.6.6
  cloud_firestore: ^4.15.5

  # time-dateFormat :
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
     - assets/image/